// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-002(guest)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-002(guest)', async function() {
    await driver.get("https://banihiddenparadiseresort.onrender.com/")
    await driver.manage().window().setRect({ width: 1470, height: 849 })
    await driver.findElement(By.linkText("Reservations")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2025-01-21")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2025-01-24")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div/div[3]/div/div/select")).click()
    {
      const dropdown = await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div/div[3]/div/div/select"))
      await dropdown.findElement(By.xpath("//option[. = '3']")).click()
    }
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div/div[4]/div/div/select")).click()
    {
      const dropdown = await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div/div[4]/div/div/select"))
      await dropdown.findElement(By.xpath("//option[. = '2']")).click()
    }
    await driver.findElement(By.css(".p-2")).click()
    await driver.findElement(By.css(".flex:nth-child(4) > .ml-5")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[7]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[7]/div/div/input")).sendKeys("Joehanna")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[8]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[8]/div/div/input")).sendKeys("Cansino")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[9]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[9]/div/div/input")).sendKeys("cansinojoehanna@gmail.com")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[10]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[10]/div/div/input")).sendKeys("09172345678")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[11]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div[3]/div[3]/div/form/div[11]/div/div/input")).sendKeys("Pampanga")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    await driver.findElement(By.css(".top-2")).click()
  })
})
