// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-004', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-004', async function() {
    await driver.get("https://bani-admin.onrender.com/login")
    await driver.manage().window().setRect({ width: 1470, height: 849 })
    await driver.findElement(By.linkText("Log Out")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("admin@example.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("admintest123")
    await driver.findElement(By.css(".bg-sky-950")).click()
    await driver.findElement(By.xpath("//button[@id=\'mantine-nm89npcay-tab-view\']/span")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(11) svg")).click()
    {
      const element = await driver.findElement(By.css(".m_4e7aa4fd:nth-child(11) svg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.xpath("//form/div/div/input")).click()
    await driver.findElement(By.xpath("//form/div/div/input")).sendKeys("9600")
    await driver.findElement(By.xpath("//div[2]/div/input")).click()
    await driver.findElement(By.xpath("//div[2]/div/input")).click()
    await driver.findElement(By.xpath("//form/div/div/input")).sendKeys("9900")
    await driver.findElement(By.xpath("//div[2]/div/input")).click()
    await driver.findElement(By.xpath("//div[2]/div/input")).sendKeys("5000")
    await driver.findElement(By.xpath("//textarea")).click()
    await driver.findElement(By.xpath("//textarea")).sendKeys("added 1 extra bed through email")
    await driver.findElement(By.css(".m_4081bf90 .m_811560b9")).click()
    await driver.findElement(By.xpath("//span[contains(.,\'All Reservations\')]")).click()
    await driver.findElement(By.xpath("//div[@id=\'mantine-8bp3lguca\']/div/button[2]")).click()
    await driver.findElement(By.linkText("Log Out")).click()
  })
})
