// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-003', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-003', async function() {
    await driver.get("https://bani-admin.onrender.com/login")
    await driver.manage().window().setRect({ width: 1470, height: 849 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("admin@example.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("admintest123")
    await driver.findElement(By.css(".bg-sky-950")).click()
    await driver.findElement(By.xpath("//span[contains(.,\'All Reservations\')]")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(4) path:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".m_4e7aa4fd:nth-child(4) path:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.xpath("//select")).click()
    {
      const dropdown = await driver.findElement(By.xpath("//select"))
      await dropdown.findElement(By.xpath("//option[. = 'Cancelled']")).click()
    }
    await driver.findElement(By.xpath("//textarea")).click()
    await driver.findElement(By.xpath("//textarea")).click()
    await driver.findElement(By.xpath("//textarea")).sendKeys("Change of mind")
    await driver.findElement(By.css(".m_4081bf90 .m_811560b9")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/header/div/div/a[2]")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div/header/div/div/a")).click()
    await driver.findElement(By.xpath("//span[contains(.,\'All Reservations\')]")).click()
    {
      const element = await driver.findElement(By.xpath("//span[contains(.,\'All Reservations\')]"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Reservation History")).click()
    await driver.findElement(By.linkText("Log Out")).click()
  })
})
