// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-001(admin)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-001(admin)', async function() {
    await driver.get("https://bani-admin.onrender.com/login")
    await driver.manage().window().setRect({ width: 1470, height: 832 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("admin@example.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("admintest123")
    await driver.findElement(By.css(".bg-sky-950")).click()
    await driver.findElement(By.xpath("//button[2]/span")).click()
    await driver.findElement(By.xpath("//button[@id=\'mantine-pgx2c0ism-tab-today\']/span")).click()
    await driver.findElement(By.linkText("Log Out")).click()
  })
})
