// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-001(guest)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-001(guest)', async function() {
    await driver.get("https://bani-admin.onrender.com/login/")
    await driver.manage().window().setRect({ width: 1320, height: 849 })
    await driver.findElement(By.linkText("Reservations")).click()
    await driver.executeScript("window.scrollTo(0,384)")
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(1) > .p-1")).sendKeys("2025-01-01")
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .p-1")).sendKeys("2025-01-03")
    await driver.findElement(By.css(".p-2")).click()
    await driver.findElement(By.css(".flex:nth-child(2) > .ml-5")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[7]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[7]/div/div/input")).sendKeys("Joehanna")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[8]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[8]/div/div/input")).sendKeys("Cansino")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[9]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[9]/div/div/input")).sendKeys("jhnnacansino@gmail.com")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[10]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[10]/div/div/input")).sendKeys("09123456789")
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[11]/div/div/input")).click()
    await driver.findElement(By.xpath("//div[@id=\'root\']/div[3]/div/div[3]/div/div[2]/div/div/div[3]/div/form/div[11]/div/div/input")).sendKeys("Manila")
    await driver.findElement(By.css(".bg-\\[\\#CBA989\\]")).click()
    await driver.findElement(By.css(".top-2")).click()
  })
})
