// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-014- Retrieve and Display Available Rooms', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-014- Retrieve and Display Available Rooms', async function() {
    await driver.get("https://bani-admin.onrender.com/login")
    await driver.manage().window().setRect({ width: 1265, height: 1372 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("admin@example.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("admintest123")
    await driver.findElement(By.css(".bg-sky-950")).click()
    await driver.findElement(By.linkText("Rooms")).click()
    await driver.findElement(By.css(".m_4e7aa4f3:nth-child(2) .mrt-table-head-cell-labels .tabler-icon")).click()
    await driver.findElement(By.css(".m_4e7aa4f3:nth-child(3) .mrt-table-head-cell-labels .tabler-icon")).click()
    await driver.findElement(By.css(".m_4e7aa4f3:nth-child(4) .mrt-table-head-cell-labels .tabler-icon")).click()
    await driver.findElement(By.css(".m_4e7aa4f3:nth-child(5) .mrt-table-head-cell-labels .tabler-icon")).click()
    await driver.findElement(By.css(".m_4e7aa4f3:nth-child(6) .mrt-table-head-cell-labels .tabler-icon")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(1) > .m_4e7aa4ef path:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".m_4e7aa4fd:nth-child(1) > .m_4e7aa4ef path:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".m_606cb269 > svg")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(1) > .m_4e7aa4ef .m_8d3afb97")).click()
    {
      const element = await driver.findElement(By.css(".m_4e7aa4fd:nth-child(1) > .m_4e7aa4ef .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".m_606cb269 path"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".m_606cb269 > svg"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".m_606cb269 > svg")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(2) .m_8d3afb97")).click()
    {
      const element = await driver.findElement(By.css(".m_4e7aa4fd:nth-child(2) .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".m_606cb269 > svg")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(5) svg")).click()
    {
      const element = await driver.findElement(By.css(".m_4e7aa4fd:nth-child(5) svg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".m_811560b9")).click()
    await driver.findElement(By.css(".m_606cb269 > svg")).click()
    {
      const element = await driver.findElement(By.css(".tabler-icon-maximize"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".tabler-icon-maximize")).click()
    await driver.findElement(By.css(".tabler-icon-minimize")).click()
    {
      const element = await driver.findElement(By.css(".mantine-focus-auto:nth-child(5)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".mantine-focus-auto:nth-child(4) > .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".tabler-icon-baseline-density-medium")).click()
    await driver.findElement(By.css(".tabler-icon-baseline-density-small > path:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.id("mantine-ih2up04bi-target"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("path:nth-child(6)")).click()
    await driver.findElement(By.css("path:nth-child(6)")).click()
    await driver.findElement(By.css("path:nth-child(6)")).click()
    await driver.findElement(By.css(".mantine-focus-auto:nth-child(5) .m_93039a1d")).click()
    await driver.findElement(By.css(".mantine-focus-auto:nth-child(6) .m_93039a1d")).click()
    await driver.findElement(By.css(".mantine-active .m_811560b9")).click()
    {
      const element = await driver.findElement(By.css(".mantine-active:nth-child(5)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".mantine-focus-auto:nth-child(4) > .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.id("mantine-ih2up04bi-target"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".mrt-toolbar-internal-buttons > .mantine-focus-auto:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".tabler-icon-filter")).click()
    {
      const element = await driver.findElement(By.css("#mantine-ih2up04bi-target > .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css("path:nth-child(8)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".mrt-toolbar-internal-buttons > .mantine-focus-auto:nth-child(2) > .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".tabler-icon-filter-off"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".tabler-icon-filter-off > path:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".tabler-icon-filter-off")).click()
    {
      const element = await driver.findElement(By.css(".mrt-toolbar-internal-buttons > .mantine-focus-auto:nth-child(1) > .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".m_8d3afb97 > .tabler-icon-search")).click()
    await driver.findElement(By.linkText("Log Out")).click()
    await driver.close()
  })
})
