// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-008-Login Functionality - Invalid Credentials Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-008-Login Functionality - Invalid Credentials Test', async function() {
    await driver.get("https://bani-admin.onrender.com/login")
    await driver.manage().window().setRect({ width: 1265, height: 1372 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("admin123@example.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("wrongPassword123")
    await driver.findElement(By.css(".bg-sky-950")).click()
  })
})
