// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-010- Toggle Dashboard Density (Compact vs. Comfortable View)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-010- Toggle Dashboard Density (Compact vs. Comfortable View)', async function() {
    await driver.get("https://bani-admin.onrender.com/")
    await driver.manage().window().setRect({ width: 1294, height: 1392 })
    await driver.findElement(By.css("#mantine-mos9pburc-tab-view > .mantine-Tabs-tabLabel")).click()
    {
      const element = await driver.findElement(By.css(".\\__m__-rho > .mantine-focus-auto:nth-child(4) > .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".\\__m__-rho > .mantine-focus-auto:nth-child(4) > .m_8d3afb97")).click()
    {
      const element = await driver.findElement(By.css(".\\__m__-rho > .mantine-focus-auto:nth-child(4) > .m_8d3afb97"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".tabler-icon-baseline-density-small")).click()
    {
      const element = await driver.findElement(By.css(".tabler-icon-baseline-density-large"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".tabler-icon-baseline-density-large")).click()
    await driver.close()
  })
})
