// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-009- Full Screen Toggle Functionality Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-009- Full Screen Toggle Functionality Test', async function() {
    await driver.get("https://bani-admin.onrender.com/login")
    await driver.manage().window().setRect({ width: 1294, height: 1399 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("admin@example.com")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("admintest123")
    await driver.findElement(By.css(".bg-sky-950")).click()
    {
      const element = await driver.findElement(By.xpath("//button[2]/span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("#mantine-h6s5493wc-tab-view > .mantine-Tabs-tabLabel")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".\\__m__-rho > .mantine-focus-auto:nth-child(5)")).click()
    await driver.findElement(By.css(".tabler-icon-minimize")).click()
    await driver.findElement(By.linkText("Log Out")).click()
  })
})
