// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TID-A-015- Retrieve Rooms from MongoDB', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TID-A-015- Retrieve Rooms from MongoDB', async function() {
    await driver.get("https://bani-admin.onrender.com/")
    await driver.manage().window().setRect({ width: 1265, height: 1372 })
    await driver.findElement(By.linkText("Rooms")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(1) > .m_4e7aa4ef:nth-child(4)")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(2) > .m_4e7aa4ef:nth-child(4)")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(3) > .m_4e7aa4ef:nth-child(4)")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(4) > .m_4e7aa4ef:nth-child(4)")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(5) > .m_4e7aa4ef:nth-child(4)")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(6) > .m_4e7aa4ef:nth-child(4)")).click()
    await driver.findElement(By.css(".m_4e7aa4fd:nth-child(7) > .m_4e7aa4ef:nth-child(4)")).click()
    await driver.close()
  })
})
